import React from 'react'
import Image from 'next/image'
const page = () => {
  return (
    <div>
<div className="flex items-center justify-center text-center"> <div className="flex flex-col p-2 m-2 max-w-7xl"> <div className="text-3xl font-medium bg-blue-700">online marketing</div> <div className="text-sm mx-2 md:text-xl  text-blue-600">big sale.</div> <div className="text-sm mx-2 md:text-xl mb-2 text-stone-500">Resource person of Tailblocks communinty</div> <div className="flex items-center justify-center md:flex-row flex-col space-x-4 p-2"> <div className="flex items-center ml-4 md:ml-0 space-x-2 px-6 py-2 md:w-1/3 w-full "> <div className="md:h-40 h-28 w-28 md:w-40 rounded-full overflow-hidden bg-gray-200"> <Image src="/ssd.jpeg "width={555}height={555} alt="" className="" /> </div> <div className="flex-col"> <div className="text-lg font-medium text-stone-600 cursor-pointer hover:text-stone-400">glasses</div> <div className=" italic text-gray-500">CEO, Tailblocks</div> </div> </div> <div className="flex items-center space-x-2 px-6 py-2 md:w-1/3 w-full "> <div className="md:h-40 h-28 w-28 md:w-40 rounded-full overflow-hidden bg-gray-200"> <Image src="/kk.jpeg"width={666}height={666} alt="" className="" /> </div> <div className="flex-col"> <div className="text-lg font-medium text-stone-600 cursor-pointer hover:text-stone-400">jacket</div> <div className=" italic text-gray-500">Executive </div> </div> </div> <div className="flex items-center space-x-2 px-6 py-2 md:w-1/3 w-full "> <div className="md:h-40 h-28 w-28 md:w-40 rounded-full overflow-hidden bg-gray-200"> <Image src="/jj.jpeg"width={444}height={444} alt="" className="" /> </div> <div className="flex-col"> <div className="text-lg font-medium text-stone-600 cursor-pointer hover:text-stone-400">jacket</div> <div className=" italic text-gray-500">HR</div> </div> </div> </div> <div className="flex space-x-4 p-2 items-center justify-center md:flex-row flex-col "> <div className="flex items-center ml-4 md:ml-0 space-x-2 px-6 py-2 md:w-1/3 w-full "> <div className="md:h-40 h-28 w-28 md:w-40 rounded-full overflow-hidden bg-gray-200"> <Image src="/hg.jpeg"width={666}height={777} alt="" className="" /> </div> <div className="flex-col"> <div className="text-lg font-medium text-stone-600 cursor-pointer hover:text-stone-400">head phone</div> <div className=" italic text-gray-500">Manager</div> </div> </div> <div className="flex items-center space-x-2 px-6 py-2 md:w-1/3 w-full "> <div className="md:h-40 h-28 w-28 md:w-40 rounded-full overflow-hidden bg-gray-200"> <Image src="/gt.jpeg"width={999}height={999} alt="" className="" /> </div> <div className="flex-col"> <div className="text-lg font-medium text-stone-600 cursor-pointer hover:text-stone-400">soney</div> <div className=" italic text-gray-500">Marketing </div> </div> </div> <div className="flex items-center space-x-2 px-6 py-2 md:w-1/3 w-full "> <div className="md:h-40 h-28 w-28 md:w-40 rounded-full overflow-hidden bg-gray-200"> <Image src="/hp.jpeg"width={666}height={666} alt="" className="" /> </div> <div className="flex-col">
   <div className="text-lg font-medium text-stone-600 cursor-pointer hover:text-stone-400">head phone </div>
    <div className=" italic text-gray-500">Financer</div>
     </div> </div> </div> </div>
     <button className="text-center text-end: bg-red-800 text-white">Email
     jamamanatali33@gmail.com</button> </div> <script src="https://cdn.tailwindcss.com"></script> <script src="https://use.fontawesome.com/03f8a0ebd4.js"></script> <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script> <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
    </div>
  )
}

export default page

